Repository VictorOsterman/Projinda, pull requests merged in 2022-05, with the labels that each got.

#12 Create world
  core/src/com/projinda/game/Boot.java
  core/src/com/projinda/game/GameScreen.java
  core/src/com/projinda/game/PlatformGameboard.java
  desktop/src/com/projinda/game/DesktopLauncher.java
Labels: enhancement

#29 Create tiled map
  assets/maps/map0.tmx
  core/src/com/projinda/game/GameScreen.java
  core/src/helper/TiledMapHelper.java
Labels: enhancement

#40 Move one of the blocks in map
  assets/maps/map0.tmx
Labels: enhancement

#95 Modify 'Esc' - taking you to main menu instead of exiting the program
  core/src/com/projinda/game/GameScreen.java
Labels: enhancement

#105 Modify map0
  assets/maps/map0.tmx
Labels: enhancement

#106 Fixed bug with player standing on platform
  core/src/objects/MovingRectangle.java
  core/src/objects/Player.java
Labels: bug

#107 Add font to game over screen
  assets/fonts/score.fnt
  assets/fonts/score.png
  core/src/com/projinda/game/GameOverScreen.java
Labels: enhancement

#108 Add 'hover over' function to game over screen options
  core/src/com/projinda/game/GameOverScreen.java
Labels: enhancement

#109 Improved player movement
  assets/maps/map0.tmx
  assets/pictures/transparent.png
  core/src/com/projinda/game/GameContactListener.java
  core/src/objects/MovingRectangle.java
  core/src/objects/Player.java
Labels: enhancement

#112 Changed platforms to have a fixed range
  core/src/objects/MovingPlatform.java
  core/src/scenes/ScoreBoard.java
Labels: enhancement

#114 Improved spawning of enemies and safes
  assets/maps/map0.tmx
  core/src/com/projinda/game/GameContactListener.java
  core/src/com/projinda/game/GameScreen.java
  core/src/helper/TiledMapHelper.java
  core/src/objects/Enemy.java
  core/src/objects/MoneyItems.java
  core/src/objects/MovingPlatform.java
  core/src/objects/MovingRectangle.java
  core/src/objects/Player.java
  core/src/objects/Safe.java
Labels: enhancement

#118 Iss102
  core/src/com/projinda/game/GameScreen.java
  core/src/helper/BodyHelper.java
  core/src/helper/Const.java
  core/src/helper/TiledMapHelper.java
  core/src/objects/Coin.java
  core/src/objects/MovingRectangle.java
  core/src/objects/Player.java
Labels: enhancement

#119 Made bullets collidable with static platforms
  core/src/objects/Player.java
Labels: enhancement

#122 Safe generate coins
  core/src/objects/Bullet.java
  core/src/objects/Coin.java
  core/src/objects/MoneyItems.java
  core/src/objects/MovingRectangle.java
  core/src/objects/Player.java
  core/src/objects/Safe.java
Labels: enhancement

#124 Implement enemy shooting
  assets/laser.png
  core/src/com/projinda/game/GameContactListener.java
  core/src/com/projinda/game/GameScreen.java
  core/src/helper/Const.java
  core/src/helper/ContactType.java
  core/src/helper/TiledMapHelper.java
  core/src/objects/Bullet.java
  core/src/objects/Enemy.java
  core/src/objects/Player.java
Labels: enhancement

#126 Add a short sleep after clicking a button to prevent 'next screen clicking'
  core/src/com/projinda/game/GameOverScreen.java
  core/src/com/projinda/game/MainMenuScreen.java
Labels: bug

#127 Improve sound effects
  assets/coin.mp3
  assets/laser.mp3
  core/src/com/projinda/game/GameContactListener.java
  core/src/com/projinda/game/GameScreen.java
  core/src/objects/Bullet.java
  core/src/objects/Enemy.java
  core/src/objects/MoneyItems.java
  core/src/objects/Player.java
Labels: enhancement

#128 Documented code
  core/src/com/projinda/game/GameContactListener.java
  core/src/com/projinda/game/GameScreen.java
  core/src/helper/Const.java
  core/src/objects/Bullet.java
  core/src/objects/Coin.java
  core/src/objects/Enemy.java
  core/src/objects/MoneyItems.java
  core/src/objects/MovingPlatform.java
  core/src/objects/MovingRectangle.java
  core/src/objects/Player.java
  core/src/objects/Safe.java
  core/src/scenes/ScoreBoard.java
Labels: documentation

#129 Set safes' value to 0
  core/src/objects/Safe.java
Labels: enhancement

#130 Removed unnecessary Random object
  core/src/objects/Safe.java
Labels: enhancement

#132 Improved map, made enemies smaller
  assets/maps/map0.tmx
  core/src/com/projinda/game/GameScreen.java
Labels: enhancement

#133 Improve readme
  README.MD
  assets/instructions.png
Labels: documentation
